wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/confrez/rl/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1681800463.490954
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.8.10
      5: 0.13.4
      8:
      - 5
      9:
        2: tianshou
