task_name: 'pklot'
checkpoint: ''
wandb_activate: True
wandb_group: ''
wandb_name: confrez-tianshou
wandb_entity: 'chengtianyue'
wandb_project: 'confrez-tianshou'

num_agents: 4
num_train_envs: 1
num_test_envs: 1

seed: 42

buffer_size: 100000

max_epoch: 10000
step_per_epoch: 500
step_per_collect: 10
episode_per_test: 1
batch_size: 64
update_per_step: 0.1

discount_factor: 0.99
estimation_step: 4